### ISSUE TITLE
Octoservices Weekly Updates 2021-02-19

### ISSUE THREAD

**Issue by scottdensmore** [github/octoservices#2]
We need updates on Admin Experiences, Docs Eng, Site Eng, Octoshift and Hiring / Training.

Should look something like they do for [dsp](https://github.com/orgs/github/teams/dsp/discussions/35)

**Comment by scottdensmore** [comment]
Each blurb should be something like 
### Intro
<Celebrate.. general info>
### Updates
<What Shipped / Learned>
### Insights
<How is our product growing etc>
### Risks
<Any risks... like GHES slipping>
### Up Next
<What are we doing next>


All this is just a guideline but the idea is we do this so we can post on Fridays

**Comment by chiedo** [comment]
## ✏️  Docs Engineering

- We finished [moving from AWS S3 to Azure Blob Storage](https://github.com/github/docs-engineering/issues/272#issuecomment-778454406)! 
- We had two [site outages last week](https://github.com/github/availability/issues/1446) related to our use of Redis and are working on hardening our application against Redis failures in addition to leaving Azure Redis (It's become unreliable for a 2nd time in a few weeks)
- We remediated a Learning Lab bug that we learned about from [this bug bounty](https://github.com/github/learning-lab/issues/2676).
- We pushed back [our plans to reduce our Heroku usage on Docs](https://github.com/github/docs-engineering/issues/276#issuecomment-783503282) to focus on confidence in the stability of Docs before reducing resources.
- We wrapped up our [new looker dashboard for Docs](https://looker.githubapp.com/dashboards/2060) in [this effort](https://github.com/github/docs-engineering/issues/271#issuecomment-783523243)
- We experimented with approaches to developing a [new and more usable navigation for Docs](https://github.com/github/docs-engineering/issues/269#issuecomment-781419478).

## 🌐  Site Engineering

- @chiedo started as the engineering manager for Site Engineering.
- We wrapped up hiring for an engineer position and made an offer to Charlotte Wen, who accepted!
- We started [plans around life after Google Analytics](https://github.com/github/site-engineering/issues/315) in the Marketing org.
- We continued to explore [new approaches](https://github.com/github/site-engineering/issues/297) to creating a better contribution experience for the ReadMe project.
